version: "3.9"
services:
  db:
    image: postgis/postgis:11-3.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/mangroveAtlasApi
    ports:
      - "3000:3000"
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    ports:
      - 1025:1025
      - 8025:8025
