version: '3'
services:
  api:
    build:
      context: .
      args:
        - env=development
    command: bin/rails s -p 3000 -b '0.0.0.0'
    container_name: mangroves_api_dev
    volumes:
      - "./app:/usr/src/api/app"
      - "./vendor:/usr/src/api/vendor"
      - "./Gemfile.lock:/usr/src/api/Gemfile.lock"
