shared:                                                   
  1.1a: date                                                     
  1.1b: str                                                      
  1.1c: date                                                     
  '1.2': str                                                     
  '1.3': geojson                                                 
  '2.1': array  # array of objects                                                
  '2.2': str                                                     
  '2.3': str                                                     
  '2.4': str                                                     
  '2.5': object                                       
  '2.6': str
  '2.7': object
  '2.8': object
  '2.9': str
  '3.1': object
  '3.2': object
  '3.3': object
  '4.1': str
  '4.2': array  # array of objects?
  '5.1': str
  '5.2': str
  5.2a: int  # year 
  5.2b: object
  5.2c: object
  '5.3': str
  5.3a: object
  5.3b: str
  5.3c: int  # year
  5.3d: str
  5.3e: array  # array of str
  5.3f: array  # array of objects
  5.3g: array  # array of objects
  '5.4': str
  '5.5': str
  '6.1': array  # array of objects
  '6.2': object
  6.2a: object
  6.2b: array  # array of objects
  '6.3': str
  6.3a: object
  '6.4': object
  '7.1': object
  '7.2': object
  '7.3': array  # array of objects
  '7.4': object
  '7.5': array  # array of objects
  7.5a: array  # array of objects
  '7.6': object
  '8.1': date
  '8.2': object
  '8.3': str
  '8.4': str
  8.4a: str
  8.4b: str
  8.4c: str
  '8.5': str
  8.5a: str
  '8.6': str
  '8.7': str
  '8.8': str
  '8.9': str
  '8.10': str
  '9.1': date
  '9.2': str
  9.2a: object
  '9.3': str
  9.3a: object
  9.3b: str
  '9.4': array  # array of objects
  '9.5': str
  '10.1': ''
  10.1a: date
  10.1b: date
  '10.2': array  # array of objects
  '10.3': str
  10.3a: ''
  '10.4': str
  10.4a: object
  '10.5': str
  '10.6': ''
  10.6a: object
  '10.7': array  # array of objects
  '10.8': str